baseURL = "https://icey-air.github.io/"
languageCode = "zh-cn"
title = "Icey's blog"
theme = "hugo-theme-stack"

# 简体中文界面 + 中日韩分词统计
defaultContentLanguage = "zh"
hasCJKLanguage = true

[pagination]
  pagerSize = 5

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

[params]
  mainSections = ["post"]
  rssFullContent = true
  favicon = "/images/head.png"
  SortBy = "default"

  [params.footer]
    since = 2026
    customText = ""

  [params.dateFormat]
    published = ":date_full"
    lastUpdated = ":date_full"

  [params.sidebar]
    emoji = "✏️"
    subtitle = "A blog"
    avatar = "/images/head.png"

  [params.article]
    headingAnchor = false
    math = false
    readingTime = true

    [params.article.license]
      enabled = false

  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "archives", params = { limit = 5 } },
      { type = "categories", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

  [params.opengraph.twitter]
    site = ""
    card = "summary_large_image"

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.comments]
    enabled = false

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.extensions.passthrough]
    enable = true

    [markup.goldmark.extensions.passthrough.delimiters]
      block = [["\\[", "\\]"], ["$$", "$$"]]
      inline = [["\\(", "\\)"]]

  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2

  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = -50
    [menu.main.params]
      icon = "home"

  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search"
    weight = -60
    [menu.main.params]
      icon = "search"

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives"
    weight = -70
    [menu.main.params]
      icon = "archives"

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/icey-air"
    [menu.social.params]
      icon = "brand-github"
